//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

/* Decompiled using $class-dump ./BTLEServer > BTLEServer.h */
/* class-dump can be here at http://stevenygard.com/projects/class-dump/ */
/* Run it on an x86 or 64-bit PC/MAC, not phone */

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    int _field4;
    float _field5;
    float _field6;
} CDStruct_09667650;

#pragma mark -

@protocol ANCAlertSourceDelegate <NSObject>
- (void)alertRemoved:(ANCAlert *)arg1 isSilent:(_Bool)arg2;
- (void)alertUpdated:(ANCAlert *)arg1 isSilent:(_Bool)arg2;
- (void)alertAdded:(ANCAlert *)arg1 isSilent:(_Bool)arg2;
@end

@protocol BBObserverDelegate <NSObject>

@optional
- (struct CGSize)observer:(BBObserver *)arg1 composedAttachmentSizeForType:(long long)arg2 thumbnailWidth:(float)arg3 height:(float)arg4 key:(NSString *)arg5;
- (UIImage *)observer:(BBObserver *)arg1 composedAttachmentImageForType:(long long)arg2 thumbnailData:(NSData *)arg3 key:(NSString *)arg4;
- (NSDictionary *)observer:(BBObserver *)arg1 multipleThumbnailSizeConstraintsForAttachmentType:(long long)arg2;
- (BBThumbnailSizeConstraints *)observer:(BBObserver *)arg1 thumbnailSizeConstraintsForAttachmentType:(long long)arg2;
- (_Bool)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(BBObserver *)arg1;
- (_Bool)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(BBObserver *)arg1;
- (void)observer:(BBObserver *)arg1 noteServerReceivedResponseForBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 noteServerConnectionStateChanged:(_Bool)arg2;
- (void)observer:(BBObserver *)arg1 noteInvalidatedBulletinIDs:(NSSet *)arg2;
- (void)observer:(BBObserver *)arg1 noteAlertBehaviorOverrideStateChanged:(unsigned long long)arg2;
- (void)observer:(BBObserver *)arg1 noteAlertBehaviorOverridesChanged:(unsigned long long)arg2;
- (void)observer:(BBObserver *)arg1 purgeReferencesToBulletinID:(NSString *)arg2;
- (void)observer:(BBObserver *)arg1 noteSectionParametersChanged:(BBSectionParameters *)arg2 forSectionID:(NSString *)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionInfo:(BBSectionInfo *)arg2;
- (void)observer:(BBObserver *)arg1 updateSectionInfo:(BBSectionInfo *)arg2 inCategory:(long long)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionOrder:(NSArray *)arg2;
- (void)observer:(BBObserver *)arg1 updateSectionOrder:(NSArray *)arg2 forCategory:(long long)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionOrderRule:(long long)arg2;
- (void)observer:(BBObserver *)arg1 removeBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 removeBulletin:(BBBulletin *)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(BBObserver *)arg1 modifyBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 modifyBulletin:(BBBulletin *)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(BBObserver *)arg1 addBulletin:(BBBulletin *)arg2 forFeed:(unsigned long long)arg3;
@end

@protocol CBCentralManagerDelegate <NSObject>
- (void)centralManagerDidUpdateState:(CBCentralManager *)arg1;

@optional
- (void)centralManager:(CBCentralManager *)arg1 didDisconnectPeripheral:(CBPeripheral *)arg2 error:(NSError *)arg3;
- (void)centralManager:(CBCentralManager *)arg1 didFailToConnectPeripheral:(CBPeripheral *)arg2 error:(NSError *)arg3;
- (void)centralManager:(CBCentralManager *)arg1 didConnectPeripheral:(CBPeripheral *)arg2;
- (void)centralManager:(CBCentralManager *)arg1 didDiscoverPeripheral:(CBPeripheral *)arg2 advertisementData:(NSDictionary *)arg3 RSSI:(NSNumber *)arg4;
- (void)centralManager:(CBCentralManager *)arg1 didRetrieveConnectedPeripherals:(NSArray *)arg2;
- (void)centralManager:(CBCentralManager *)arg1 didRetrievePeripherals:(NSArray *)arg2;
- (void)centralManager:(CBCentralManager *)arg1 willRestoreState:(NSDictionary *)arg2;
@end

@protocol CBPeripheralDelegate <NSObject>

@optional
- (void)peripheral:(CBPeripheral *)arg1 didWriteValueForDescriptor:(CBDescriptor *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didUpdateValueForDescriptor:(CBDescriptor *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverDescriptorsForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didUpdateNotificationStateForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didWriteValueForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didUpdateValueForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverCharacteristicsForService:(CBService *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverIncludedServicesForService:(CBService *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverServices:(NSError *)arg2;
- (void)peripheralDidUpdateRSSI:(CBPeripheral *)arg1 error:(NSError *)arg2;
- (void)peripheral:(CBPeripheral *)arg1 didModifyServices:(NSArray *)arg2;
- (void)peripheralDidInvalidateServices:(CBPeripheral *)arg1;
- (void)peripheralDidUpdateName:(CBPeripheral *)arg1;
@end

@protocol CBPeripheralManagerDelegate <NSObject>
- (void)peripheralManagerDidUpdateState:(CBPeripheralManager *)arg1;

@optional
- (void)peripheralManagerIsReadyToUpdateSubscribers:(CBPeripheralManager *)arg1;
- (void)peripheralManager:(CBPeripheralManager *)arg1 didReceiveWriteRequests:(NSArray *)arg2;
- (void)peripheralManager:(CBPeripheralManager *)arg1 didReceiveReadRequest:(CBATTRequest *)arg2;
- (void)peripheralManager:(CBPeripheralManager *)arg1 central:(CBCentral *)arg2 didUnsubscribeFromCharacteristic:(CBCharacteristic *)arg3;
- (void)peripheralManager:(CBPeripheralManager *)arg1 central:(CBCentral *)arg2 didSubscribeToCharacteristic:(CBCharacteristic *)arg3;
- (void)peripheralManager:(CBPeripheralManager *)arg1 didAddService:(CBService *)arg2 error:(NSError *)arg3;
- (void)peripheralManagerDidStartAdvertising:(CBPeripheralManager *)arg1 error:(NSError *)arg2;
- (void)peripheralManager:(CBPeripheralManager *)arg1 willRestoreState:(NSDictionary *)arg2;
@end

@protocol ClientServiceDelegate <NSObject>
- (void)clientServiceDidStart:(ClientService *)arg1;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
- (NSString *)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;

@optional
- (NSString *)debugDescription;
@end

@interface ANCNotification : NSObject
{
    unsigned int _UID;
    ANCAlert *_alert;
}

@property(readonly, nonatomic) ANCAlert *alert; // @synthesize alert=_alert;
@property(readonly, nonatomic) unsigned int UID; // @synthesize UID=_UID;
- (void)dealloc;
- (id)initWithUID:(unsigned int)arg1 alert:(id)arg2;

@end

@interface ANCService : ServerService <ANCAlertSourceDelegate>
{
    CBMutableCharacteristic *_controlPoint;
    CBMutableCharacteristic *_notificationSource;
    CBMutableCharacteristic *_dataSource;
    unsigned int _uidGenerator;
    NSMutableDictionary *_uidMap;
    NSMutableDictionary *_alertMap;
    ANCAlertSource *_alertSource;
    NSObject<OS_dispatch_queue> *_eventQueue;
}

- (id)appAttributeIDToString:(unsigned char)arg1;
- (id)notificationAttributeIDToString:(unsigned char)arg1;
- (id)eventFlagsToString:(unsigned char)arg1;
- (id)eventIDToString:(unsigned char)arg1;
- (id)invocationForUpdateDataSource:(id)arg1 central:(id)arg2;
- (id)responseForAppAttributeID:(unsigned char)arg1 appIdentifier:(id)arg2;
- (id)responseForNotificationAttributeID:(unsigned char)arg1 maxLength:(unsigned short)arg2 notification:(id)arg3;
- (id)responseForAttributeID:(unsigned char)arg1 maxLength:(unsigned short)arg2 attribute:(id)arg3;
- (id)notificationForAlert:(id)arg1;
- (id)notificationForUID:(unsigned int)arg1;
- (void)alertRemoved:(id)arg1 isSilent:(_Bool)arg2;
- (void)alertUpdated:(id)arg1 isSilent:(_Bool)arg2;
- (void)alertAdded:(id)arg1 isSilent:(_Bool)arg2;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)updateDataSource:(id)arg1 central:(id)arg2;
- (void)updateNotificationSource:(unsigned char)arg1 notification:(id)arg2 isSilent:(_Bool)arg3;
- (long long)handleGetAppAttributesCommand:(id)arg1;
- (long long)handleGetNotificationAttributesCommand:(id)arg1;
- (long long)handleControlPointWrite:(id)arg1;
- (void)handleWriteRequests:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface BTLEXpcConnection : NSObject
{
    NSObject<OS_xpc_object> *_connection;
}

- (void)centralDidAccessService:(id)arg1;
- (void)authenticationDidFail:(id)arg1;
- (void)authenticationDidSucceed:(id)arg1;
- (void)clientServiceManagerDidStart:(id)arg1;
- (void)sendMsg:(id)arg1 args:(id)arg2;
- (void)handlePersistServerServicesMsg:(id)arg1;
- (void)handleConnectAlwaysMsg:(id)arg1;
- (void)handleConnectOnceMsg:(id)arg1;
- (void)handleMsg:(id)arg1;
- (void)handleDisconnection;
- (void)handleEvent:(id)arg1;
- (id)initWithConnection:(id)arg1;

@end

@interface ConnectionManager : NSObject <CBCentralManagerDelegate>
{
    CBCentralManager *_centralManager;
    NSMutableDictionary *_connectOnceIdentifiersMap;
    NSArray *_connectAlwaysIdentifiers;
    NSMutableSet *_blacklistedIdentifiers;
    TransactionAssertion *_connectionAssertion;
    NSArray *_peripherals;
    NSMutableDictionary *_clientServiceManagerMap;
}

+ (id)instance;
@property(retain, nonatomic) NSArray *peripherals; // @synthesize peripherals=_peripherals;
@property(retain, nonatomic) NSArray *connectAlwaysIdentifiers; // @synthesize connectAlwaysIdentifiers=_connectAlwaysIdentifiers;
- (id)centralManagerStateString;
- (id)peripheralForIdentifier:(id)arg1;
- (void)authDidFail:(id)arg1;
- (void)authDidSucceed:(id)arg1;
- (void)pairingDidFail:(id)arg1;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)connectionTimeout:(id)arg1;
- (void)refreshConnectionAssertion;
- (void)disconnectPeripheral:(id)arg1 force:(_Bool)arg2;
- (void)connectPeripheral:(id)arg1;
- (void)refreshPeripherals;
- (id)init;
- (void)connectAlways:(id)arg1;
- (void)connectOnce:(id)arg1;

@end

@interface ANCRequest : NSObject
{
    DataInputStream *_stream;
    CBATTRequest *_master;
    NSInvocation *_action;
}

@property(retain, nonatomic) NSInvocation *action; // @synthesize action=_action;
@property(readonly, nonatomic) CBATTRequest *master; // @synthesize master=_master;
@property(readonly, nonatomic) DataInputStream *stream; // @synthesize stream=_stream;
- (void)dealloc;
- (id)initWithRequests:(id)arg1;

@end

@interface ClientServiceManager : NSObject <CBPeripheralDelegate, ClientServiceDelegate>
{
    CBPeripheral *_peripheral;
    NSMapTable *_clientServiceMap;
    unsigned long long _startPriority;
    NSMutableSet *_startingClientServices;
}

- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)peripheral:(id)arg1 didModifyServices:(id)arg2;
- (void)clientServiceDidStart:(id)arg1;
- (void)analyzeError:(id)arg1;
- (void)startClientServices;
- (void)dealloc;
- (_Bool)getDesiredConnectionParameters:(CDStruct_09667650 *)arg1;
- (id)clientServiceForUUID:(id)arg1;
- (id)initWithPeripheral:(id)arg1;

@end

@interface ClientService : NSObject <CBPeripheralDelegate>
{
    ClientServiceManager *_manager;
    CBPeripheral *_peripheral;
    CBService *_service;
    unsigned long long _priority;
    double _startTimeout;
    id <ClientServiceDelegate> _delegate;
    _Bool _isStarted;
    NSTimer *_startTimer;
}

@property(readonly, nonatomic) _Bool isStarted; // @synthesize isStarted=_isStarted;
@property(nonatomic) id <ClientServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) unsigned long long priority; // @synthesize priority=_priority;
- (void)startTimeout;
- (void)dealloc;
- (void)notifyDidStart;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;
- (CDStruct_09667650)desiredConnectionParameters;
- (_Bool)hasDesiredConnectionParameters;
- (void)stop;
- (void)start;

@end

@interface HIDService : ClientService
{
    CBCharacteristic *_reportMap;
    CBCharacteristic *_hidControlPoint;
    CBCharacteristic *_hidInformation;
    CBCharacteristic *_accessoryCategory;
    NSMapTable *_reportInfoMap;
    unsigned long long _numReports;
    struct __IOHIDUserDevice *_hidDevice;
    _Bool _hidHasSingleReportID;
    NSObject<OS_dispatch_queue> *_hidQueue;
    unsigned int _pmService;
    struct IONotificationPort *_pmNotificationPort;
    unsigned int _pmNotifier;
}

- (id)reportTypeToString:(int)arg1;
- (id)characteristicForReportID:(unsigned int)arg1 reportType:(int)arg2;
- (_Bool)hasSingleReportID;
- (void)writeControlPointCommand:(unsigned char)arg1;
- (void)handlePowerManagementNotification:(unsigned int)arg1 notificationID:(long long)arg2;
- (int)setReport:(char *)arg1 reportLength:(long long)arg2 reportID:(unsigned int)arg3 reportType:(int)arg4;
- (int)getReport:(char *)arg1 reportLength:(long long *)arg2 reportID:(unsigned int)arg3 reportType:(int)arg4;
- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)deregisterForPowerManagementEvents;
- (void)registerForPowerManagementEvents;
- (void)signalCommandCondition:(id)arg1 error:(_Bool)arg2;
- (void)destroyHIDDevice;
- (void)createHIDDevice;
- (id)hidDeviceProperties;
- (void)createReportInfo:(id)arg1;
- (void)dealloc;
- (CDStruct_09667650)desiredConnectionParameters;
- (_Bool)hasDesiredConnectionParameters;
- (void)stop;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

@interface HIDReportInfo : NSObject
{
    unsigned char _ID;
    unsigned char _type;
    NSCondition *_commandCondition;
    long long _commandPending;
    _Bool _commandError;
}

@property(nonatomic) _Bool commandError; // @synthesize commandError=_commandError;
@property(readonly, nonatomic) NSCondition *commandCondition; // @synthesize commandCondition=_commandCondition;
@property(nonatomic) long long commandPending; // @synthesize commandPending=_commandPending;
@property(readonly, nonatomic) unsigned char type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned char ID; // @synthesize ID=_ID;
- (void)dealloc;
- (id)initWithID:(unsigned char)arg1 type:(unsigned char)arg2;

@end

@interface DIService : ClientService
{
    CBCharacteristic *_serialNumber;
    CBCharacteristic *_pnpID;
    unsigned char _vendorIDSource;
    unsigned short _vendorID;
    unsigned short _productID;
    unsigned short _productVersion;
}

@property(readonly, nonatomic) unsigned short productVersion; // @synthesize productVersion=_productVersion;
@property(readonly, nonatomic) unsigned short productID; // @synthesize productID=_productID;
@property(readonly, nonatomic) unsigned short vendorID; // @synthesize vendorID=_vendorID;
@property(readonly, nonatomic) unsigned char vendorIDSource; // @synthesize vendorIDSource=_vendorIDSource;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)extractIDs;
- (void)extractSerialNumber;
- (void)dealloc;
@property(readonly, nonatomic) NSString *serialNumber; // @dynamic serialNumber;
- (_Bool)hasIDs;
- (_Bool)hasSerialNumber;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

@interface ServerServiceManager : NSObject <CBPeripheralManagerDelegate>
{
    CBPeripheralManager *_peripheralManager;
    NSMapTable *_serverServiceMap;
    _Bool _persist;
    TransactionAssertion *_persistanceAssertion;
    _Bool _shouldAdvertise;
    NSMutableArray *_pendingATTUpdates;
}

+ (id)instance;
- (id)peripheralManagerStateString;
- (void)peripheralManagerIsReadyToUpdateSubscribers:(id)arg1;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedCentrals:(id)arg3;
- (void)respondToRequest:(id)arg1 withResult:(long long)arg2;
- (void)removeService:(id)arg1;
- (void)addService:(id)arg1;
- (void)refreshPersistanceAssertion;
- (void)setupAdvertising;
- (void)destroyServices;
- (void)createServices;
- (id)init;
- (void)setShouldAdvertise:(_Bool)arg1;
- (void)setPersist:(_Bool)arg1;

@end

@interface ServerService : NSObject <CBPeripheralManagerDelegate>
{
    CBMutableService *_service;
}

@property(readonly, nonatomic) CBMutableService *service; // @synthesize service=_service;
- (void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)dealloc;
- (void)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedCentrals:(id)arg3;
- (void)respondToRequest:(id)arg1 withResult:(long long)arg2;
- (id)init;
- (void)stop;
- (void)start;

@end

@interface BTLEXpcServer : NSObject
{
    NSObject<OS_xpc_object> *_server;
}

+ (id)instance;
- (void)handleConnection:(id)arg1;
- (void)handleEvent:(id)arg1;
- (id)init;
- (void)start;

@end

@interface CTService : ServerService
{
    CBMutableCharacteristic *_currentTime;
    CBMutableCharacteristic *_localTimeInformation;
    NSTimer *_nextDSTTransitionTimer;
}

- (unsigned char)currentDstOffset;
- (BOOL)currentTimeZone;
- (void)currentTimeDidChange;
- (void)dstDidChange;
- (void)systemTimeZoneDidChange;
- (void)systemClockDidChange;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)setupNextDSTTransitionTimer;
- (id)readLocalTimeInformation;
- (id)localTimeInformationValue;
- (void)updateCurrentTime;
- (id)readCurrentTime;
- (id)currentTimeValue;
- (void)dealloc;
- (id)init;

@end

@interface AuthenticationService : ClientService
{
    CBCharacteristic *_versionCharacteristic;
    CBCharacteristic *_certificate1Characteristic;
    CBCharacteristic *_certificate2Characteristic;
    CBCharacteristic *_challengeResponseCharacteristic;
    long long _authState;
    struct __CFDictionary *_authInfo;
    NSTimer *_authTimer;
}

+ (void)initialize;
- (id)authStateString;
- (void)authenticationDidFail;
- (void)authenticationDidSucceed;
- (_Bool)verifyCertificateIsUnique;
- (id)certificateSerialNumber;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)authTimeout;
- (void)verifyChallenge;
- (void)issueChallenge;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

@interface ANCAlertSource : NSObject <BBObserverDelegate>
{
    id <ANCAlertSourceDelegate> _delegate;
    void *_addressBook;
    NSMutableDictionary *_alerts;
    NSMutableDictionary *_categoryMap;
    NSTimer *_silenceTimer;
    _Bool _doNotDisturb;
    BBObserver *_bbObserver;
    NSMutableDictionary *_bbBulletins;
    struct __CFArray *_ctRingingCalls;
    struct __CFArray *_ctUnreadMissedCalls;
    NSMutableArray *_vvUnreadVoicemails;
}

@property(nonatomic) id <ANCAlertSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned char)categoryIDForGenreID:(unsigned long long)arg1;
- (unsigned long long)genreIDForGenre:(id)arg1;
- (void)setArray:(id)arg1 withArray:(id)arg2 objectRemoved:(CDUnknownBlockType)arg3 objectAdded:(CDUnknownBlockType)arg4;
- (void)unreadVoicemailsChanged;
- (void)callHistoryChanged;
- (void)callIdentificationChanged:(struct __CTCall *)arg1;
- (void)callStatusChanged;
- (unsigned char)categoryIDForAppIdentifier:(id)arg1;
- (id)alertWithBulletin:(id)arg1;
- (void)observer:(id)arg1 noteInvalidatedBulletinIDs:(id)arg2;
- (void)observer:(id)arg1 noteAlertBehaviorOverrideStateChanged:(unsigned long long)arg2;
- (void)observer:(id)arg1 removeBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(id)arg1 modifyBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(id)arg1 addBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)removeAlert:(id)arg1;
- (void)updateAlert:(id)arg1;
- (_Bool)isSilent;
- (void)silenceTimer;
- (void)dealloc;
- (id)alertsForCategoryID:(unsigned char)arg1;
- (id)init;

@end

@interface ANCAlert : NSObject <NSCopying>
{
    unsigned char _categoryID;
}

@property(readonly, nonatomic) unsigned char categoryID; // @synthesize categoryID=_categoryID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToAlert:(id)arg1;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (_Bool)isImportant;
- (id)initWithCategoryID:(unsigned char)arg1;

@end

@interface ANCBulletinAlert : ANCAlert
{
    BBBulletin *_bulletin;
}

- (unsigned long long)hash;
- (_Bool)isEqualToAlert:(id)arg1;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (_Bool)isImportant;
- (void)dealloc;
- (id)initWithBulletin:(id)arg1 categoryID:(unsigned char)arg2;

@end

@interface ANCCallAlert : ANCAlert
{
    struct __CTCall *_call;
    void *_addressBook;
}

- (unsigned long long)hash;
- (id)date;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (_Bool)isPhoneNumber:(struct __CFString *)arg1;
- (void)dealloc;
- (id)initWithCall:(struct __CTCall *)arg1 addressBook:(void *)arg2 categoryID:(unsigned char)arg3;

@end

@interface ANCIncomingCallAlert : ANCCallAlert
{
}

- (_Bool)isEqualToAlert:(id)arg1;
- (id)message;
- (_Bool)isImportant;
- (id)initWithCall:(struct __CTCall *)arg1 addressBook:(void *)arg2;

@end

@interface ANCMissedCallAlert : ANCCallAlert
{
}

- (_Bool)isEqualToAlert:(id)arg1;
- (id)message;
- (id)initWithCall:(struct __CTCall *)arg1 addressBook:(void *)arg2;

@end

@interface ANCVoicemailAlert : ANCAlert
{
    VMVoicemail *_voicemail;
    void *_addressBook;
}

- (unsigned long long)hash;
- (_Bool)isEqualToAlert:(id)arg1;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (void)dealloc;
- (id)initWithVoicemail:(id)arg1 addressBook:(void *)arg2;

@end

@interface BatteryClientService : ClientService
{
    CBCharacteristic *_batteryLevel;
}

- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)dealloc;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

@interface BatteryServerService : ServerService
{
    CBMutableCharacteristic *_batteryLevel;
    unsigned char _batteryLevelCachedValue;
    struct IONotificationPort *_ioNotificationPort;
    unsigned int _ioNotifier;
}

- (void)batteryStatusChanged:(unsigned int)arg1 notify:(_Bool)arg2;
- (void)batteryReadyChanged:(unsigned int)arg1 notify:(_Bool)arg2;
- (void)deregisterForBatteryEvents;
- (void)registerForBatteryEvents;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)updateBatterylevel;
- (id)batteryLevelValue;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)init;

@end

@interface DataInputStream : NSObject
{
    NSInputStream *_stream;
    long long _byteOrder;
}

+ (id)inputStreamWithData:(id)arg1 byteOrder:(long long)arg2;
+ (id)inputStreamWithData:(id)arg1;
- (_Bool)readString:(id)arg1;
- (_Bool)readUint32:(unsigned int *)arg1;
- (_Bool)readUint16:(unsigned short *)arg1;
- (_Bool)readUint8:(char *)arg1;
- (void)dealloc;
- (id)initWithValue:(id)arg1 byteOrder:(long long)arg2;

@end

@interface DataOutputStream : NSObject
{
    NSMutableData *_stream;
    long long _byteOrder;
}

+ (id)outputStreamWithByteOrder:(long long)arg1;
+ (id)outputStream;
- (id)data;
- (void)writeBytes:(const void *)arg1 length:(unsigned long long)arg2;
- (void)writeData:(id)arg1;
- (void)writeUint32:(unsigned int)arg1;
- (void)writeUint16:(unsigned short)arg1;
- (void)writeUint8:(unsigned char)arg1;
- (void)dealloc;
- (id)initWithByteOrder:(long long)arg1;

@end

@interface ATTUpdate : NSObject
{
    NSData *_value;
    CBMutableCharacteristic *_characteristic;
    NSArray *_centrals;
}

+ (id)updateWithValue:(id)arg1 characteristic:(id)arg2 centrals:(id)arg3;
@property(readonly, nonatomic) NSArray *centrals; // @synthesize centrals=_centrals;
@property(readonly, nonatomic) CBMutableCharacteristic *characteristic; // @synthesize characteristic=_characteristic;
@property(readonly, nonatomic) NSData *value; // @synthesize value=_value;
- (void)dealloc;
- (id)initWithValue:(id)arg1 characteristic:(id)arg2 centrals:(id)arg3;

@end

@interface TransactionAssertion : NSObject
{
}

- (void)dealloc;
- (id)init;

@end

@interface NSBundle (BTLEServer)
+ (id)mobileBluetoothBundle;
@end

@interface NSMapTable (BTLEServer)
- (void)enumerateKeysAndObjectsUsingBlock:(CDUnknownBlockType)arg1;
@end

@interface NSMutableSet (BTLEServer)
- (_Bool)removeSubscriber:(id)arg1;
- (_Bool)addSubscriber:(id)arg1;
@end

