//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark -

//
// File: BTLEServer
// UUID: AC94A88C-D7EC-3C36-BC1E-A60F9C26684B
//
//                           Arch: arm64
//                 Source version: 109.52.0.0.0
//            Minimum iOS version: 8.1.0
//                    SDK version: 8.1.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol ANCAlertSourceDelegate <NSObject>
- (void)alertRemoved:(ANCAlert *)arg1 isSilent:(_Bool)arg2;
- (void)alertModified:(ANCAlert *)arg1 isSilent:(_Bool)arg2;
- (void)alertAdded:(ANCAlert *)arg1 isSilent:(_Bool)arg2 isPreExisting:(_Bool)arg3;
@end

@protocol BBObserverDelegate <NSObject>

@optional
- (struct CGSize)observer:(BBObserver *)arg1 composedAttachmentSizeForType:(long long)arg2 thumbnailWidth:(float)arg3 height:(float)arg4 key:(NSString *)arg5;
- (UIImage *)observer:(BBObserver *)arg1 composedAttachmentImageForType:(long long)arg2 thumbnailData:(NSData *)arg3 key:(NSString *)arg4;
- (NSDictionary *)observer:(BBObserver *)arg1 multipleThumbnailSizeConstraintsForAttachmentType:(long long)arg2;
- (BBThumbnailSizeConstraints *)observer:(BBObserver *)arg1 thumbnailSizeConstraintsForAttachmentType:(long long)arg2;
- (_Bool)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(BBObserver *)arg1;
- (_Bool)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(BBObserver *)arg1;
- (void)observer:(BBObserver *)arg1 noteServerReceivedResponseForBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 noteServerConnectionStateChanged:(_Bool)arg2;
- (void)observer:(BBObserver *)arg1 noteInvalidatedBulletinIDs:(NSSet *)arg2;
- (void)observer:(BBObserver *)arg1 noteAlertBehaviorOverrideStateChanged:(unsigned long long)arg2;
- (void)observer:(BBObserver *)arg1 noteAlertBehaviorOverridesChanged:(unsigned long long)arg2;
- (void)observer:(BBObserver *)arg1 purgeReferencesToBulletinID:(NSString *)arg2;
- (void)observer:(BBObserver *)arg1 noteSectionParametersChanged:(BBSectionParameters *)arg2 forSectionID:(NSString *)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionInfo:(BBSectionInfo *)arg2;
- (void)observer:(BBObserver *)arg1 updateSectionInfo:(BBSectionInfo *)arg2 inCategory:(long long)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionOrder:(NSArray *)arg2;
- (void)observer:(BBObserver *)arg1 updateSectionOrder:(NSArray *)arg2 forCategory:(long long)arg3;
- (void)observer:(BBObserver *)arg1 updateSectionOrderRule:(long long)arg2;
- (void)observer:(BBObserver *)arg1 removeBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 removeBulletin:(BBBulletin *)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(BBObserver *)arg1 modifyBulletin:(BBBulletin *)arg2;
- (void)observer:(BBObserver *)arg1 modifyBulletin:(BBBulletin *)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(BBObserver *)arg1 addBulletin:(BBBulletin *)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(BBObserver *)arg1 addBulletin:(BBBulletin *)arg2 forFeed:(unsigned long long)arg3 playLightsAndSirens:(_Bool)arg4 withReply:(void (^)(_Bool))arg5;
@end

@protocol CBCentralManagerDelegate <NSObject>
- (void)centralManagerDidUpdateState:(CBCentralManager *)arg1;

@optional
- (void)centralManager:(CBCentralManager *)arg1 didDisconnectPeripheral:(CBPeripheral *)arg2 error:(NSError *)arg3;
- (void)centralManager:(CBCentralManager *)arg1 didFailToConnectPeripheral:(CBPeripheral *)arg2 error:(NSError *)arg3;
- (void)centralManager:(CBCentralManager *)arg1 didConnectPeripheral:(CBPeripheral *)arg2;
- (void)centralManager:(CBCentralManager *)arg1 didDiscoverPeripheral:(CBPeripheral *)arg2 advertisementData:(NSDictionary *)arg3 RSSI:(NSNumber *)arg4;
- (void)centralManager:(CBCentralManager *)arg1 didRetrieveConnectedPeripherals:(NSArray *)arg2;
- (void)centralManager:(CBCentralManager *)arg1 didRetrievePeripherals:(NSArray *)arg2;
- (void)centralManager:(CBCentralManager *)arg1 willRestoreState:(NSDictionary *)arg2;
@end

@protocol CBPeripheralDelegate <NSObject>

@optional
- (void)peripheral:(CBPeripheral *)arg1 didWriteValueForDescriptor:(CBDescriptor *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didUpdateValueForDescriptor:(CBDescriptor *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverDescriptorsForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didUpdateNotificationStateForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didWriteValueForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didUpdateValueForCharacteristic:(CBCharacteristic *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverCharacteristicsForService:(CBService *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverIncludedServicesForService:(CBService *)arg2 error:(NSError *)arg3;
- (void)peripheral:(CBPeripheral *)arg1 didDiscoverServices:(NSError *)arg2;
- (void)peripheral:(CBPeripheral *)arg1 didReadRSSI:(NSNumber *)arg2 error:(NSError *)arg3;
- (void)peripheralDidUpdateRSSI:(CBPeripheral *)arg1 error:(NSError *)arg2;
- (void)peripheral:(CBPeripheral *)arg1 didModifyServices:(NSArray *)arg2;
- (void)peripheralDidInvalidateServices:(CBPeripheral *)arg1;
- (void)peripheralDidUpdateName:(CBPeripheral *)arg1;
@end

@protocol CBPeripheralManagerDelegate <NSObject>
- (void)peripheralManagerDidUpdateState:(CBPeripheralManager *)arg1;

@optional
- (void)peripheralManagerIsReadyToUpdateSubscribers:(CBPeripheralManager *)arg1;
- (void)peripheralManager:(CBPeripheralManager *)arg1 didReceiveWriteRequests:(NSArray *)arg2;
- (void)peripheralManager:(CBPeripheralManager *)arg1 didReceiveReadRequest:(CBATTRequest *)arg2;
- (void)peripheralManager:(CBPeripheralManager *)arg1 central:(CBCentral *)arg2 didUnsubscribeFromCharacteristic:(CBCharacteristic *)arg3;
- (void)peripheralManager:(CBPeripheralManager *)arg1 central:(CBCentral *)arg2 didSubscribeToCharacteristic:(CBCharacteristic *)arg3;
- (void)peripheralManager:(CBPeripheralManager *)arg1 didAddService:(CBService *)arg2 error:(NSError *)arg3;
- (void)peripheralManagerDidStartAdvertising:(CBPeripheralManager *)arg1 error:(NSError *)arg2;
- (void)peripheralManager:(CBPeripheralManager *)arg1 willRestoreState:(NSDictionary *)arg2;
@end

@protocol CBScalablePipeManagerDelegate <NSObject>
- (void)scalablePipeManager:(CBScalablePipeManager *)arg1 pipeDidDisconnect:(CBScalablePipe *)arg2 error:(NSError *)arg3;
- (void)scalablePipeManager:(CBScalablePipeManager *)arg1 pipeDidConnect:(CBScalablePipe *)arg2;
- (void)scalablePipeManager:(CBScalablePipeManager *)arg1 didUnregisterEndpoint:(NSString *)arg2;
- (void)scalablePipeManager:(CBScalablePipeManager *)arg1 didRegisterEndpoint:(NSString *)arg2 error:(NSError *)arg3;
- (void)scalablePipeManagerDidUpdateState:(CBScalablePipeManager *)arg1;

@optional
- (void)scalablePipeManager:(CBScalablePipeManager *)arg1 pipeClogged:(CBScalablePipe *)arg2 cleanedCompletionHandler:(void (^)(void))arg3;
@end

@protocol HIDDeviceDelegate <NSObject>
- (int)setReportData:(NSData *)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (int)getReportData:(id *)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (void)desiredConnectionParametersDidChange;
- (void)hidDeviceDidStop;
- (void)hidDeviceDidStart;
@end

@protocol MediaInfoDelegate <NSObject>
- (void)mediaVolumeDidChange;
- (void)mediaInfoDidChange;
- (void)mediaStateDidChange;
- (void)mediaPlayerDidChange;
- (void)supportedCommandsDidChange;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (_Bool)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSStreamDelegate <NSObject>

@optional
- (void)stream:(NSStream *)arg1 handleEvent:(unsigned long long)arg2;
@end

@protocol PipeDelegate <NSObject>
- (void)pipe:(Pipe *)arg1 didReceiveMessage:(NSDictionary *)arg2;
@end

@interface EndpointManager : NSObject <CBScalablePipeManagerDelegate>
{
    _Bool _persist;
    CBScalablePipeManager *_pipeManager;
    DeviceManagementEndpoint *_deviceManagementEndpoint;
    TransactionAssertion *_persistanceAssertion;
}

+ (id)instance;
@property(retain, nonatomic) TransactionAssertion *persistanceAssertion; // @synthesize persistanceAssertion=_persistanceAssertion;
@property(nonatomic) _Bool persist; // @synthesize persist=_persist;
@property(retain, nonatomic) DeviceManagementEndpoint *deviceManagementEndpoint; // @synthesize deviceManagementEndpoint=_deviceManagementEndpoint;
@property(retain, nonatomic) CBScalablePipeManager *pipeManager; // @synthesize pipeManager=_pipeManager;
- (id)scalablePipeManagerStateString;
- (id)endpointForPipe:(id)arg1;
- (void)scalablePipeManager:(id)arg1 pipeDidDisconnect:(id)arg2 error:(id)arg3;
- (void)scalablePipeManager:(id)arg1 pipeDidConnect:(id)arg2;
- (void)scalablePipeManager:(id)arg1 didUnregisterEndpoint:(id)arg2;
- (void)scalablePipeManager:(id)arg1 didRegisterEndpoint:(id)arg2 error:(id)arg3;
- (void)scalablePipeManagerDidUpdateState:(id)arg1;
- (void)refreshPersistanceAssertion;
- (id)init;
- (void)disconnectDevice:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DeviceManagementEndpoint : Endpoint
{
}

- (void)handleDisconnectClassicDeviceCommand:(id)arg1 message:(id)arg2;
- (void)disconnectDevice:(id)arg1;
- (id)init;

@end

@interface ANCNotification : NSObject
{
    unsigned int _UID;
    ANCAlert *_alert;
    _Bool _isDirty;
}

@property(nonatomic) _Bool isDirty; // @synthesize isDirty=_isDirty;
@property(readonly, nonatomic) ANCAlert *alert; // @synthesize alert=_alert;
@property(readonly, nonatomic) unsigned int UID; // @synthesize UID=_UID;
- (void)dealloc;
- (id)initWithUID:(unsigned int)arg1 alert:(id)arg2;

@end

@interface PeripheralConnectionInfo : NSObject
{
    unsigned long long _tryCount;
}

@property(nonatomic) unsigned long long tryCount; // @synthesize tryCount=_tryCount;
- (id)init;

@end

@interface HIDSingleReportDevice : HIDDevice
{
}

- (int)setReport:(char *)arg1 reportLength:(long long)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (int)getReport:(char *)arg1 reportLength:(long long *)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (void)handleReportData:(id)arg1 reportID:(unsigned char)arg2;

@end

@interface HIDDevice : NSObject
{
    id <HIDDeviceDelegate> _delegate;
    _Bool _isStarted;
    _Bool _isStopped;
    struct __IOHIDUserDevice *_device;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)hidDeviceWithDelegate:(id)arg1 properties:(id)arg2 hasMultipleReportIDs:(_Bool)arg3;
@property(readonly, nonatomic) _Bool isStarted; // @synthesize isStarted=_isStarted;
- (int)setReport:(char *)arg1 reportLength:(long long)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (int)getReport:(char *)arg1 reportLength:(long long *)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (void)notifyDidStart;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 properties:(id)arg2;
- (id)initWithDelegate:(id)arg1;
- (void)handleReportData:(id)arg1 reportID:(unsigned char)arg2;
- (id)desiredConnectionParameters;
- (void)stop;
- (void)start;

@end

@interface ANCService : ServerService <ANCAlertSourceDelegate>
{
    CBMutableCharacteristic *_controlPoint;
    CBMutableCharacteristic *_notificationSource;
    CBMutableCharacteristic *_dataSource;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableSet *_activeCentrals;
    unsigned int _uidGenerator;
    NSMutableDictionary *_uidMap;
    NSMutableDictionary *_alertMap;
    ANCAlertSource *_alertSource;
}

@property(retain, nonatomic) ANCAlertSource *alertSource; // @synthesize alertSource=_alertSource;
@property(retain, nonatomic) NSMutableDictionary *alertMap; // @synthesize alertMap=_alertMap;
@property(retain, nonatomic) NSMutableDictionary *uidMap; // @synthesize uidMap=_uidMap;
@property(retain, nonatomic) NSMutableSet *activeCentrals; // @synthesize activeCentrals=_activeCentrals;
- (id)appAttributeIDToString:(unsigned char)arg1;
- (id)notificationAttributeIDToString:(unsigned char)arg1;
- (id)eventFlagsToString:(unsigned char)arg1;
- (id)categoryIDToString:(unsigned char)arg1;
- (id)eventIDToString:(unsigned char)arg1;
- (id)invocationForUpdateDataSource:(id)arg1 central:(id)arg2;
- (id)responseForAppAttributeID:(unsigned char)arg1 appIdentifier:(id)arg2;
- (id)responseForNotificationAttributeID:(unsigned char)arg1 maxLength:(unsigned short)arg2 notification:(id)arg3;
- (id)responseForAttributeID:(unsigned char)arg1 maxLength:(unsigned short)arg2 attribute:(id)arg3;
- (id)notificationForAlert:(id)arg1;
- (id)notificationForUID:(unsigned int)arg1;
- (void)alertRemoved:(id)arg1 isSilent:(_Bool)arg2;
- (void)alertModified:(id)arg1 isSilent:(_Bool)arg2;
- (void)alertAdded:(id)arg1 isSilent:(_Bool)arg2 isPreExisting:(_Bool)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)stopNotifications;
- (void)startNotifications;
- (void)updateDataSource:(id)arg1 central:(id)arg2;
- (void)updateNotificationSource:(unsigned char)arg1 notification:(id)arg2 sourceFlags:(unsigned char)arg3 centrals:(id)arg4;
- (void)updateNotificationSource:(unsigned char)arg1 notification:(id)arg2 sourceFlags:(unsigned char)arg3;
- (long long)handlePerformNotificationActionCommand:(id)arg1;
- (long long)handleGetAppAttributesCommand:(id)arg1;
- (long long)handleGetNotificationAttributesCommand:(id)arg1;
- (long long)handleControlPointWrite:(id)arg1;
- (void)handleWriteRequests:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface BTLEXpcConnection : NSObject
{
    NSObject<OS_xpc_object> *_connection;
}

- (void)deviceDisconnectionRequested:(id)arg1;
- (void)peerIsNotUsingBuiltinService:(id)arg1;
- (void)peerIsUsingBuiltinService:(id)arg1;
- (void)authenticationDidFail:(id)arg1;
- (void)authenticationDidSucceed:(id)arg1;
- (void)peripheralConnectionParametersDidChange:(id)arg1;
- (void)sendMsg:(id)arg1 args:(id)arg2;
- (void)handleDisconnectClassicDeviceMsg:(id)arg1;
- (void)handlePersistServerServicesMsg:(id)arg1;
- (void)handleConnectAlwaysMsg:(id)arg1;
- (void)handleConnectOnceMsg:(id)arg1;
- (void)handleMsg:(id)arg1;
- (void)handleDisconnection;
- (void)handleEvent:(id)arg1;
- (id)initWithConnection:(id)arg1;

@end

@interface MediaRegistration : NSObject
{
    NSString *_lastKnownAttributeValue;
}

@property(retain, nonatomic) NSString *lastKnownAttributeValue; // @synthesize lastKnownAttributeValue=_lastKnownAttributeValue;
- (void)dealloc;
- (id)init;

@end

@interface ConnectionManager : NSObject <CBCentralManagerDelegate>
{
    CBCentralManager *_centralManager;
    NSMutableDictionary *_connectOnceIdentifiersMap;
    NSMutableDictionary *_connectAlwaysIdentifiersMap;
    NSMutableSet *_blacklistedIdentifiers;
    TransactionAssertion *_connectionAssertion;
    NSArray *_peripherals;
    NSMutableDictionary *_clientServiceManagerMap;
}

+ (id)instance;
@property(retain, nonatomic) NSArray *peripherals; // @synthesize peripherals=_peripherals;
@property(retain, nonatomic) NSMutableDictionary *connectAlwaysIdentifiersMap; // @synthesize connectAlwaysIdentifiersMap=_connectAlwaysIdentifiersMap;
- (id)centralManagerStateString;
- (void)peerIsUsingBuiltinService:(id)arg1;
- (void)authDidFail:(id)arg1;
- (void)authDidSucceed:(id)arg1;
- (void)peripheralPairingDidFail:(id)arg1;
- (void)peripheralDidCompleteConnection:(id)arg1;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)connectionTimeout:(id)arg1;
- (void)refreshConnectionAssertion;
- (void)disconnectPeripheral:(id)arg1 force:(_Bool)arg2;
- (void)connectPeripheral:(id)arg1;
- (void)refreshPeripherals;
- (id)init;
- (id)peripheralForIdentifier:(id)arg1;
- (void)connectAlways:(id)arg1;
- (void)connectOnce:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface MediaSession : ServerService
{
    NSSet *_lastKnownSupportedCommands;
    NSMutableDictionary *_registrations;
    unsigned char _loadedEntityID;
    unsigned char _loadedAttributeID;
}

@property(nonatomic) unsigned char loadedAttributeID; // @synthesize loadedAttributeID=_loadedAttributeID;
@property(nonatomic) unsigned char loadedEntityID; // @synthesize loadedEntityID=_loadedEntityID;
@property(retain, nonatomic) NSSet *lastKnownSupportedCommands; // @synthesize lastKnownSupportedCommands=_lastKnownSupportedCommands;
- (id)registrationForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)lastKnownAttributeValueForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (void)setLastKnownAttributeValue:(id)arg1 attributeID:(unsigned char)arg2 entityID:(unsigned char)arg3;
- (_Bool)isRegisteredForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)notifiableAttributeIDs:(id)arg1 entityID:(unsigned char)arg2;
- (void)setRegisteredAttributeIDs:(id)arg1 entityID:(unsigned char)arg2;
- (void)dealloc;
- (id)init;

@end

@interface Endpoint : NSObject <PipeDelegate>
{
    NSString *_identifier;
    long long _type;
    long long _priority;
    NSSet *_supportedCommands;
    NSMutableSet *_pipes;
}

@property(readonly, retain, nonatomic) NSMutableSet *pipes; // @synthesize pipes=_pipes;
@property(readonly, nonatomic) NSSet *supportedCommands; // @synthesize supportedCommands=_supportedCommands;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)pipe:(id)arg1 didReceiveMessage:(id)arg2;
- (void)removePipe:(id)arg1;
- (void)addPipe:(id)arg1;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1 supportedCommands:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface MediaService : ServerService <MediaInfoDelegate>
{
    CBMutableCharacteristic *_remoteCommand;
    CBMutableCharacteristic *_entityUpdate;
    CBMutableCharacteristic *_entityAttribute;
    NSMutableDictionary *_sessions;
    MediaInfo *_info;
}

@property(retain, nonatomic) MediaInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) NSMutableDictionary *sessions; // @synthesize sessions=_sessions;
- (id)entityUpdateFlagsToString:(unsigned char)arg1;
- (id)attributeIDToString:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)remoteCommandIDToString:(unsigned char)arg1;
- (id)invocationForNotifyAttributeIDs:(id)arg1 entityID:(unsigned char)arg2 central:(id)arg3;
- (id)currentAttributeValueForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)sessionForCentral:(id)arg1;
- (unsigned long long)subscriptionCount;
- (void)mediaVolumeDidChange;
- (void)mediaInfoDidChange;
- (void)mediaStateDidChange;
- (void)mediaPlayerDidChange;
- (void)supportedCommandsDidChange;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)stopNotifications;
- (void)startNotifications;
- (void)attributeIDsDidChange:(id)arg1 entityID:(unsigned char)arg2;
- (void)supportedCommandsDidChange:(id)arg1;
- (void)notifyAttributeIDs:(id)arg1 entityID:(unsigned char)arg2 central:(id)arg3;
- (void)notifySupportedCommands:(id)arg1 central:(id)arg2;
- (void)notifyAttributeValue:(id)arg1 attributeID:(unsigned char)arg2 entityID:(unsigned char)arg3 central:(id)arg4;
- (void)notifySupportedCommandsValue:(id)arg1 central:(id)arg2;
- (long long)handleEntityAttributeWrite:(id)arg1;
- (long long)handleEntityAttributeRead:(id)arg1;
- (long long)handleEntityUpdateWrite:(id)arg1 action:(id *)arg2;
- (long long)handleRemoteCommandWrite:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface OutboundMessage : NSObject
{
    NSData *_data;
    unsigned long long _offset;
}

@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void)dealloc;
- (id)initWithData:(id)arg1;

@end

@interface Pipe : NSObject <NSStreamDelegate>
{
    id <PipeDelegate> _delegate;
    CBScalablePipe *_pipe;
    NSSet *_supportedCommands;
    NSMutableArray *_txMessageQueue;
    NSMutableData *_receivedMessage;
    NSMutableData *_incomingBuffer;
}

@property(retain, nonatomic) NSMutableData *incomingBuffer; // @synthesize incomingBuffer=_incomingBuffer;
@property(retain, nonatomic) NSMutableData *receivedMessage; // @synthesize receivedMessage=_receivedMessage;
@property(retain, nonatomic) NSMutableArray *txMessageQueue; // @synthesize txMessageQueue=_txMessageQueue;
@property(retain, nonatomic) NSSet *supportedCommands; // @synthesize supportedCommands=_supportedCommands;
@property(readonly, retain, nonatomic) CBScalablePipe *pipe; // @synthesize pipe=_pipe;
@property(readonly, nonatomic) id <PipeDelegate> delegate; // @synthesize delegate=_delegate;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)receiveMessage:(char *)arg1 length:(long long)arg2;
- (void)sendNextQueuedMessage;
- (void)sendMessage:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 pipe:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface ANCRequest : NSObject
{
    DataInputStream *_stream;
    CBATTRequest *_master;
    NSInvocation *_action;
}

@property(retain, nonatomic) NSInvocation *action; // @synthesize action=_action;
@property(readonly, nonatomic) CBATTRequest *master; // @synthesize master=_master;
@property(readonly, nonatomic) DataInputStream *stream; // @synthesize stream=_stream;
- (void)dealloc;
- (id)initWithRequests:(id)arg1;

@end

@interface ClientServiceManager : NSObject <CBPeripheralDelegate>
{
    CBPeripheral *_peripheral;
    NSMapTable *_clientServiceMap;
    unsigned long long _startPriority;
    NSMutableSet *_startingClientServices;
}

+ (void)initialize;
- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)peripheral:(id)arg1 didModifyServices:(id)arg2;
- (void)analyzeError:(id)arg1;
- (void)startClientServices;
- (void)dealloc;
- (void)clientService:(id)arg1 desiresConnectionParameters:(id)arg2;
- (void)clientServiceDidStart:(id)arg1;
- (id)clientServiceForUUID:(id)arg1;
- (id)initWithPeripheral:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface ClientService : NSObject <CBPeripheralDelegate>
{
    ClientServiceManager *_manager;
    CBPeripheral *_peripheral;
    CBService *_service;
    _Bool _isPrimary;
    unsigned long long _priority;
    double _startTimeout;
    _Bool _isStarted;
    NSTimer *_startTimer;
}

+ (id)UUID;
@property(readonly, nonatomic) _Bool isStarted; // @synthesize isStarted=_isStarted;
@property(readonly, nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) _Bool isPrimary; // @synthesize isPrimary=_isPrimary;
- (void)startTimeout;
- (void)dealloc;
- (void)notifyDidStart;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;
- (void)stop;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface HIDService : ClientService <HIDDeviceDelegate>
{
    CBCharacteristic *_reportMap;
    CBCharacteristic *_hidControlPoint;
    CBCharacteristic *_hidInformation;
    CBCharacteristic *_accessoryCategory;
    NSMapTable *_reportInfoMap;
    unsigned long long _numReports;
    HIDDevice *_hidDevice;
    unsigned int _pmService;
    struct IONotificationPort *_pmNotificationPort;
    unsigned int _pmNotifier;
}

+ (id)UUID;
- (id)reportTypeToString:(int)arg1;
- (id)characteristicForReportID:(unsigned int)arg1 reportType:(int)arg2;
- (_Bool)allInputReportsReady;
- (_Bool)hasMultipleReportIDs;
- (void)writeControlPointCommand:(unsigned char)arg1;
- (void)handlePowerManagementNotification:(unsigned int)arg1 notificationID:(long long)arg2;
- (int)setReportData:(id)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (int)getReportData:(id *)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (void)desiredConnectionParametersDidChange;
- (void)hidDeviceDidStop;
- (void)hidDeviceDidStart;
- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)notifyDidStartIfEverythingReady;
- (void)deregisterForPowerManagementEvents;
- (void)registerForPowerManagementEvents;
- (void)signalCommandCondition:(id)arg1 error:(_Bool)arg2;
- (void)destroyHIDDevice;
- (void)createHIDDeviceIfEverythingReady;
- (id)hidDeviceProperties;
- (void)createReportInfo:(id)arg1;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface HIDReportInfo : NSObject
{
    unsigned char _ID;
    unsigned char _type;
    _Bool _isValid;
    NSCondition *_commandCondition;
    long long _commandPending;
    _Bool _commandError;
}

@property(nonatomic) _Bool commandError; // @synthesize commandError=_commandError;
@property(readonly, nonatomic) NSCondition *commandCondition; // @synthesize commandCondition=_commandCondition;
@property(nonatomic) long long commandPending; // @synthesize commandPending=_commandPending;
@property(nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(readonly, nonatomic) unsigned char type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned char ID; // @synthesize ID=_ID;
- (void)dealloc;
- (id)initWithID:(unsigned char)arg1 type:(unsigned char)arg2;

@end

@interface DIService : ClientService
{
    CBCharacteristic *_pnpID;
    CBCharacteristic *_fwRevision;
    unsigned char _vendorIDSource;
    unsigned short _vendorID;
    unsigned short _productID;
    unsigned short _productVersion;
}

+ (id)UUID;
@property(readonly, nonatomic) unsigned short productVersion; // @synthesize productVersion=_productVersion;
@property(readonly, nonatomic) unsigned short productID; // @synthesize productID=_productID;
@property(readonly, nonatomic) unsigned short vendorID; // @synthesize vendorID=_vendorID;
@property(readonly, nonatomic) unsigned char vendorIDSource; // @synthesize vendorIDSource=_vendorIDSource;
- (id)vendorIDSourceString;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)extractIDs;
- (void)dealloc;
@property(readonly, nonatomic) NSString *firmwareRevision; // @dynamic firmwareRevision;
- (_Bool)hasIDs;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

@interface ServerServiceManager : NSObject <CBPeripheralManagerDelegate>
{
    CBPeripheralManager *_peripheralManager;
    NSMapTable *_serverServiceMap;
    _Bool _persist;
    TransactionAssertion *_persistanceAssertion;
    NSMutableArray *_pendingATTUpdates;
}

+ (void)initialize;
+ (id)instance;
- (id)peripheralManagerStateString;
- (id)nameForCentral:(id)arg1;
- (void)peripheralManagerIsReadyToUpdateSubscribers:(id)arg1;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedCentrals:(id)arg3;
- (void)respondToRequest:(id)arg1 withResult:(long long)arg2;
- (void)removeService:(id)arg1;
- (void)addService:(id)arg1;
- (void)refreshPersistanceAssertion;
- (void)destroyServices;
- (void)createServices;
- (id)init;
- (void)setPersist:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface ServerService : NSObject <CBPeripheralManagerDelegate>
{
    CBMutableService *_service;
}

@property(readonly, nonatomic) CBMutableService *service; // @synthesize service=_service;
- (void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)dealloc;
- (void)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedCentrals:(id)arg3;
- (void)respondToRequest:(id)arg1 withResult:(long long)arg2;
- (id)init;
- (void)stop;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface BTLEXpcServer : NSObject
{
    NSObject<OS_xpc_object> *_server;
}

+ (id)instance;
- (void)handleConnection:(id)arg1;
- (void)handleEvent:(id)arg1;
- (id)init;
- (void)start;

@end

@interface HIDMultiReportsDevice : HIDDevice
{
}

- (int)setReport:(char *)arg1 reportLength:(long long)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (int)getReport:(char *)arg1 reportLength:(long long *)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (void)handleReportData:(id)arg1 reportID:(unsigned char)arg2;

@end

@interface CTService : ServerService
{
    CBMutableCharacteristic *_currentTime;
    CBMutableCharacteristic *_localTimeInformation;
    NSTimer *_nextDSTTransitionTimer;
}

- (unsigned char)currentDstOffset;
- (BOOL)currentTimeZone;
- (void)currentTimeDidChange;
- (void)dstDidChange;
- (void)significantTimeChange;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)stopNotifications;
- (void)startNotifications;
- (void)setupNextDSTTransitionTimer;
- (void)cancelNextDSTTransitionTimer;
- (id)readLocalTimeInformation;
- (id)localTimeInformationValue;
- (void)updateCurrentTime;
- (id)readCurrentTime;
- (id)currentTimeValue;
- (void)dealloc;
- (void)stop;
- (id)init;

@end

@interface AuthenticationService : ClientService
{
    CBCharacteristic *_versionCharacteristic;
    CBCharacteristic *_certificate1Characteristic;
    CBCharacteristic *_certificate2Characteristic;
    CBCharacteristic *_challengeResponseCharacteristic;
    long long _authState;
    struct __CFDictionary *_authInfo;
    NSTimer *_authTimer;
}

+ (void)initialize;
+ (id)UUID;
- (id)authStateString;
- (void)authenticationDidFail;
- (void)authenticationDidSucceed;
- (_Bool)verifyCertificateIsUnique;
- (id)certificateSerialNumber;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)authTimeout;
- (void)verifyChallenge;
- (void)issueChallenge;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

@interface ANCAlertSource : NSObject <BBObserverDelegate>
{
    id <ANCAlertSourceDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_queue;
    NSDictionary *_1stPartyAppIdentifierToCategoryMap;
    void *_addressBook;
    NSMutableDictionary *_alerts;
    NSMutableDictionary *_appIdentifierToCategoryCache;
    _Bool _bbDoNotDisturb;
    NSMutableDictionary *_bbBulletinAlerts;
    BBObserver *_bbObserver;
    NSMutableArray *_ctRingingCalls;
    NSMapTable *_ctIncomingCallAlerts;
    NSMutableArray *_chUnreadMissedCalls;
    NSMutableDictionary *_chMissedCallAlerts;
    CHManager *_chManager;
    NSMutableArray *_vvUnreadVoicemails;
    NSMapTable *_vvVoicemailAlerts;
}

- (unsigned char)categoryIDForGenreID:(unsigned long long)arg1;
- (unsigned long long)genreIDForGenre:(id)arg1;
- (void)combineCurrentArray:(id)arg1 withNewArray:(id)arg2 maxCount:(unsigned long long)arg3 objectRemoved:(CDUnknownBlockType)arg4 objectAdded:(CDUnknownBlockType)arg5;
- (void)addressBookChanged;
- (void)unreadVoicemailsChanged:(_Bool)arg1;
- (void)unreadVoicemailsChangedNotification;
- (void)callHistoryChanged:(_Bool)arg1;
- (void)callHistoryChangedNotification;
- (void)callIdentificationChanged:(id)arg1;
- (void)callStatusChanged;
- (unsigned char)categoryIDForAppIdentifier:(id)arg1;
- (_Bool)isSpecialSectionID:(id)arg1;
- (void)observer:(id)arg1 noteInvalidatedBulletinIDs:(id)arg2;
- (void)observer:(id)arg1 noteAlertBehaviorOverrideStateChanged:(unsigned long long)arg2;
- (void)observer:(id)arg1 removeBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(id)arg1 modifyBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(id)arg1 addBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)removeAlert:(id)arg1;
- (void)modifyAlert:(id)arg1;
- (void)addAlert:(id)arg1 isPreExisting:(_Bool)arg2;
- (void)dealloc;
- (id)displayNameForAppIdentifier:(id)arg1;
- (id)alertsForCategoryID:(unsigned char)arg1;
- (void)invalidate;
- (id)initWithDelegate:(id)arg1 queue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface ANCAlert : NSObject <NSCopying>
{
    unsigned char _categoryID;
}

@property(readonly, nonatomic) unsigned char categoryID; // @synthesize categoryID=_categoryID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)performNegativeAction;
- (_Bool)performPositiveAction;
- (id)negativeActionLabel;
- (id)positiveActionLabel;
- (_Bool)hasNegativeAction;
- (_Bool)hasPositiveAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (_Bool)isImportant;
- (id)initWithCategoryID:(unsigned char)arg1;

@end

@interface ANCBulletinAlert : ANCAlert
{
    BBBulletin *_bulletin;
    BBObserver *_observer;
}

@property(retain, nonatomic) BBBulletin *bulletin; // @synthesize bulletin=_bulletin;
- (_Bool)performNegativeAction;
- (id)negativeActionLabel;
- (_Bool)hasNegativeAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (void)dealloc;
- (id)initWithBulletin:(id)arg1 observer:(id)arg2 categoryID:(unsigned char)arg3;

@end

@interface ANCIncomingCallAlert : ANCAlert
{
    struct __CTCall *_call;
    void *_addressBook;
}

- (_Bool)performNegativeAction;
- (_Bool)performPositiveAction;
- (id)negativeActionLabel;
- (id)positiveActionLabel;
- (_Bool)hasNegativeAction;cd
- (_Bool)hasPositiveAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (_Bool)isImportant;
- (_Bool)isPhoneNumber:(struct __CFString *)arg1;
- (void)dealloc;
- (id)initWithCall:(struct __CTCall *)arg1 addressBook:(void *)arg2;

@end

@interface ANCMissedCallAlert : ANCAlert
{
    CHRecentCall *_recentCall;
    CHManager *_manager;
}

- (_Bool)performNegativeAction;
- (_Bool)performPositiveAction;
- (id)negativeActionLabel;
- (id)positiveActionLabel;
- (_Bool)hasNegativeAction;
- (_Bool)hasPositiveAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (void)dealloc;
- (id)initWithRecentCall:(id)arg1 manager:(id)arg2;

@end

@interface ANCVoicemailAlert : ANCAlert
{
    VMVoicemail *_voicemail;
    void *_addressBook;
}

- (_Bool)performNegativeAction;
- (_Bool)performPositiveAction;
- (id)negativeActionLabel;
- (id)positiveActionLabel;
- (_Bool)hasNegativeAction;
- (_Bool)hasPositiveAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (void)dealloc;
- (id)initWithVoicemail:(id)arg1 addressBook:(void *)arg2;

@end

@interface ConnectionParameters : NSObject
{
    float _minInterval;
    float _preferredInterval;
    float _maxInterval;
    int _pairs;
    float _latency;
    float _timeout;
}

@property(nonatomic) float timeout; // @synthesize timeout=_timeout;
@property(nonatomic) float latency; // @synthesize latency=_latency;
@property(nonatomic) int pairs; // @synthesize pairs=_pairs;
@property(nonatomic) float maxInterval; // @synthesize maxInterval=_maxInterval;
@property(nonatomic) float preferredInterval; // @synthesize preferredInterval=_preferredInterval;
@property(nonatomic) float minInterval; // @synthesize minInterval=_minInterval;

@end

@interface BatteryClientService : ClientService
{
    CBCharacteristic *_batteryLevel;
    CBCharacteristic *_batteryPowerState;
}

+ (id)UUID;
- (id)batteryPowerStateString:(unsigned char)arg1;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)dealloc;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

@interface BatteryServerService : ServerService
{
    CBMutableCharacteristic *_batteryLevel;
    int _iopsNotifyPercentChangeToken;
}

- (void)batteryLevelDidChange;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)stopNotifications;
- (void)startNotifications;
- (void)updateBatterylevel;
- (id)batteryLevelValue;
- (void)dealloc;
- (void)stop;
- (id)init;

@end

@interface MediaInfo : NSObject
{
    id <MediaInfoDelegate> _delegate;
    struct __CFArray *_currentSupportedCommands;
    NSString *_currentIdentifier;
    _Bool _currentIsPlaying;
    NSDictionary *_currentInfo;
}

@property(retain, nonatomic) NSDictionary *currentInfo; // @synthesize currentInfo=_currentInfo;
@property(retain, nonatomic) NSString *currentIdentifier; // @synthesize currentIdentifier=_currentIdentifier;
@property(nonatomic) id <MediaInfoDelegate> delegate; // @synthesize delegate=_delegate;
- (float)defaultPlaybackRate;
- (float)playbackRate;
- (void)avServerConnectionDiedNotification;
- (void)avEffectiveVolumeDidChangeNotification:(id)arg1;
- (void)mrInfoDidChangeNotification;
- (void)mrIsPlayingDidChangeNotification:(id)arg1;
- (void)mrApplicationDidChangeNotification:(id)arg1;
- (void)mrSupportedCommandsDidChangeNotification;
- (void)volumeDidChangeForCategory:(id)arg1;
- (void)infoDidChange:(id)arg1;
- (void)isPlayingDidChange:(_Bool)arg1;
- (void)applicationDidChange:(int)arg1;
- (void)supportedCommandsDidChange:(struct __CFArray *)arg1;
- (void)unregisterForAVNotifications;
- (void)registerForAVNotifications;
- (void)dealloc;
- (id)trackDuration;
- (id)trackTitle;
- (id)trackAlbum;
- (id)trackArtist;
- (id)queueRepeatMode;
- (id)queueShuffleMode;
- (id)queueCount;
- (id)queueIndex;
- (float)playerPlaybackRate;
- (id)playerElapsedTime;
- (id)playerVolume;
- (id)playerPlaybackState;
- (id)playerName;
- (id)supportedCommands;
- (id)init;

@end

@interface DataInputStream : NSObject
{
    NSInputStream *_stream;
    long long _byteOrder;
}

+ (id)inputStreamWithData:(id)arg1 byteOrder:(long long)arg2;
+ (id)inputStreamWithData:(id)arg1;
- (_Bool)readString:(id)arg1;
- (_Bool)readUint32:(unsigned int *)arg1;
- (_Bool)readUint16:(unsigned short *)arg1;
- (_Bool)readUint8:(char *)arg1;
- (void)dealloc;
- (id)initWithValue:(id)arg1 byteOrder:(long long)arg2;

@end

@interface DataOutputStream : NSObject
{
    NSMutableData *_stream;
    long long _byteOrder;
}

+ (id)outputStreamWithByteOrder:(long long)arg1;
+ (id)outputStream;
- (id)data;
- (void)writeString:(id)arg1;
- (void)writeBytes:(const void *)arg1 length:(unsigned long long)arg2;
- (void)writeData:(id)arg1;
- (void)writeUint32:(unsigned int)arg1;
- (void)writeUint16:(unsigned short)arg1;
- (void)writeUint8:(unsigned char)arg1;
- (void)dealloc;
- (id)initWithByteOrder:(long long)arg1;

@end

@interface ATTUpdate : NSObject
{
    NSData *_value;
    CBMutableCharacteristic *_characteristic;
    NSArray *_centrals;
}

+ (id)updateWithValue:(id)arg1 characteristic:(id)arg2 centrals:(id)arg3;
@property(readonly, nonatomic) NSArray *centrals; // @synthesize centrals=_centrals;
@property(readonly, nonatomic) CBMutableCharacteristic *characteristic; // @synthesize characteristic=_characteristic;
@property(readonly, nonatomic) NSData *value; // @synthesize value=_value;
- (void)dealloc;
- (id)initWithValue:(id)arg1 characteristic:(id)arg2 centrals:(id)arg3;

@end

@interface TransactionAssertion : NSObject
{
}

- (void)dealloc;
- (id)init;

@end

@interface NSBundle (BTLEServer)
+ (id)mobileBluetoothBundle;
@end

@interface NSString (BTLEServer)
- (id)UTF8DataWithMaxLength:(unsigned long long)arg1 isTruncated:(_Bool *)arg2;
@end

@interface NSMapTable (BTLEServer)
- (void)enumerateKeysAndObjectsUsingBlock:(CDUnknownBlockType)arg1;
@end

