ARCHS = armv7 arm64
include theos/makefiles/common.mk

BUNDLE_NAME = PebbleProfiles
PebbleProfiles_FILES = Switch.x
PebbleProfiles_FRAMEWORKS = UIKit
PebbleProfiles_LIBRARIES = flipswitch
PebbleProfiles_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk