include theos/makefiles/common.mk

BUNDLE_NAME = pebblednd
pebblednd_FILES = Switch.x
pebblednd_FRAMEWORKS = UIKit
pebblednd_LIBRARIES = flipswitch
pebblednd_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk